import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideNav from "@/components/layouts/sideNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sumisora Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp" className='scroll-smooth'>
      <body className="bg-stone-100">
        <SideNav />
        <div className="p-5 sm:!pl-[350px] flex flex-wrap items-center justify-center" id="content">
          <div className="mx-auto max-w-screen-2xl px-4 md:px-8 lg:mt-44">
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
