import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideNav from "@/components/layouts/sideNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sumisora Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp">
      <body className="bg-stone-100">
        <SideNav />
        <div className="p-5 sm:!pl-[260px] text-center" id="content">
          {/* mx-auto max-w-screen-2xl h-full */}
          {children}
        </div>
        {/* <section className="bg-slate-200 h-screen w-screen">
          <main className="mx-auto max-w-screen-2xl flex flex-col items-center justify-between">
          </main>
        </section> */}
      </body>
    </html>
  )
}
