import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideNav from "@/components/layouts/sideNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sumisora Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp" className="scroll-smooth">
      {/* <body className="bg-stone-100"> */}
      <body className="bg-brown dark:bg-gray-300 flex h-screen">
        <SideNav />
        <div
          className="sm:pl-56 p-2 flex flex-wrap items-center justify-center"
          id="content"
        >
          <div className="flex-1 overflow-auto px-4 md:px-2 lg:mt-16">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
